# Site settings
markdown: redcarpet
title: Paul K. Jackow
description: Paul Jackow's Blog
keywords: Modern, Blogging, Fun
author: Paul Jackow
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://logicliving.github.io/" # the base hostname & protocol for your site
exclude: [README.md]