# Site settings
title: Paul K. Jackow
description: Paul Jackow's Blog
keywords: Paul Jackow's Blog
author: Paul Jackow
baseurl: #"/blog" # the subpath of your site, e.g. /blog/
url: #"http://logicliving.github.io/" # the base hostname & protocol for your site
exclude: [README.md]